language: python
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.8
    env: TOXENV=py38
  - python: 3.6
    env: TOXENV=quality
  - python: 3.6
    env: TOXENV=docs
cache:
- pip
before_install:
- pip install --upgrade pip
install:
- pip install -r requirements/travis.txt
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: edx
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: "$TOXENV = quality"
  password:
    secure: J8jdAqa88CG7wFVHyK9te8Kqnf6pcOeNU/69i04KPzKU8Rbv+IQ5b0XQJS8Xsu8xny6b9e1PhZQznUjZ4NZkGfo89hy0ApT2MWSn2xKjN6NmccptZkO18uPTFyr+R5AUh/x6XOAhyjENc2mDh2AhWzVkShNodi3itlB7pJMqxQj8AosAO4OYdUj3XcNyVj0htJu5VGPhqYEegdRP6Y3S3sFcaxI/tSeLummltJne99z/eFmEMkV2GCpRGGFjB/hbey4BNAVe8g+1+ltq+pEDzUUCN1yrdkWFWxMkVOdjubtGtRWgOD8JTFNDKLQzpdaLuPHhNiZmjVElr8Czh28+EQqb7YvpCfi3ioLRCmR5nh7vD0cdvS/tpWm0C9qYRRObAIyus4N4SGS0t1TzgBAOrlQ5l8jqoqiulf6A/G8nkyXreRJcYzD/hLi5mSmTr4vHsk3+mBb70Hdb7XtI0DZc2ucP9iBYXgUO53jZoy2cY7z699/uy81MpcZrAzXLiJis9TBbwZt2C1YM92A3Tuq4gAWhnHKSjOPOA6T1uDTTaQoMh5klwSEIU8y/q51EjiBYCw43BOHhayrfl/iXA4vY4jen96tivUdqzM0ydt7EfWC3kh7xSGsZi+M9SmZRJayXEKNWg6Mbsh6b3LfAVTCF8zazq3F606eyrBVw3ZypXRg=
