language: python
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.8
    env: TOXENV=py38
  - python: 3.6
    env: TOXENV=quality
  - python: 3.6
    env: TOXENV=docs
cache:
- pip
before_install:
- pip install --upgrade pip
install:
- pip install -r requirements/travis.txt
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: __token__
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: "$TOXENV = quality"
  password:
    secure: LDgEUeQUlistSes2kUop60ogpq3wJEYcPrkp5Oeh1eQcDpwkbuzxKwwBWesghI0DRi+HhgJCM47BQGSeUjnBu7vxxEjvRyfZacyXVt+w7gnjWnsi8LMCJ7auzBWawQ2AVa4wxlYdyb8NbwjZm1nU6RISlU/u1lQcwejPnFanvJSOHEnM+Jxz8nOL45Ylltqt7GAXK7nNayxeCAx37yVcMXf6HVQJE9DLxHzLftOM+/jpOSlJAOhDoaXRbh8FLS8NdBlV4BeT+lYRJSBSj00TXmWNHGWWCiXC2asfUIn7B1bO/KNkVCBRX4EIZwGzzInaGehT2tS7PqLH+AUyNAACjsWbF3/6a+9yu3ysHwCc0y1KMrEq8i/yZwnbTTxiu2Uww1qR/IPWLo7Cn9vSZKf6N4sNdpdYzu0mpe3fyBusH+8RgeelzUmUgJZnR/2PVJlYGJWuHOk5MVGCrKijQJvKEtF7Pw6w2rrPUaD2C8yUKuujE/cSNBrVwQnvQQkqF5yXISosPXc9xMELiw3Sot9W5BUsrsx9desh+hmqoslsR0On2cVVAs18L0Mdh+gKYqzpERU5DocZB3n/vHTZuQLmHlZeVlji3ZZBM5iLfJ2g2HiPbU694N3nuN1jJEIF/dK+fOi+fhsFB9PfZVYlMOjqgK0MReE3XLK+vcjojoJrK0A=
