language: python
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.8
    env: TOXENV=py38
  - python: 3.6
    env: TOXENV=quality
  - python: 3.6
    env: TOXENV=docs
cache:
- pip
before_install:
- pip install --upgrade pip
install:
- pip install -r requirements/travis.txt
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: edx
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: "$TOXENV = quality"
  password:
    secure: CP+TNlFskXDtTHfu9sJiEkbpnw5CZaaiLcvZ7W1mh0Goj32dTYoaSbk+PdTm515+RAYDz76MitG/zvZzzII/l6VZaGmZhJl4DSFSenl5vEfuThdDZG4M3Gx2Qa/J4ZCPTUEXDDF7DawXsbozDBmGOeBWeL/pDn7JiUc2idOtd+FCO3lMRtj0XsAmy2/Hc/De3HpV0IHGGK2sD77U3Av3tKJcVitr1NOp4/f+uKV1dTFOFtb238opEoPjNkpcMAYKbGj3DLGsyNyHllEqN440clqwh4j0fdGRNmJWi/24ZCYjL0U3xMfwqJypqxmOlt6r7DJGZtVDX3A4UN3D01ZSnIpa8BozuSDxkUpiC7ZBu3h/EFdW6IXSxC5y7bEN1FXsKk13adzgRu1r/ECR4JvNo5eE4qtoLsE0hefW6M51TiJarBGvZA8ZyTAvUp5UbH9VCKGV8VQI/rFzqJxGkHtExiXOTK+HRFNiEmLWTyTydqKG1zKz5OHaZejMDVK1PjYjgPMmui4fNpAn7ytUWBVbkbRWssz6WCYfrs34O1fF48EbgveAO8Mg/Br0yY7jfsRnJItNq2okz3XLWLt8JPxSTNohFtATy5KFHxg6r4w1JDX3EiIjx/5N388gKM3fA/5CAvM/j9aAUYFqjV4Nh5xh72eOXBqWRdGyjd0MqA6+ck0=
